// ==UserScript==
// @name          Douyu Cleaner 清爽斗鱼
// @namespace     http://userstyles.org
// @description	  1.去除了直播页面一些广告/首页也进行了部分调整
// @author        Another_Dreams
// @homepage      https://userstyles.org/styles/132037
// @include       http://douyu.com/*
// @include       https://douyu.com/*
// @include       http://*.douyu.com/*
// @include       https://*.douyu.com/*
// @include       https://www.douyu.com/directory*
// @include       https://www.douyu.com/room/my_follow*
// @include       http://douyu.com/*
// @include       https://douyu.com/*
// @include       http://*.douyu.com/*
// @include       https://*.douyu.com/*
// @include       https://www.douyu.com/cms/zt/*
// @include       http://douyu.com/*
// @include       https://douyu.com/*
// @include       http://*.douyu.com/*
// @include       https://*.douyu.com/*
// @include       http://douyu.com/*
// @include       https://douyu.com/*
// @include       http://*.douyu.com/*
// @include       https://*.douyu.com/*
// @run-at        document-start
// @version       0.20190322112648
// ==/UserScript==
(function() {var css = "";
if (false || (document.domain == "douyu.com" || document.domain.substring(document.domain.indexOf(".douyu.com") + 1) == "douyu.com"))
	css += [
		"/*====================================================",
		"                Douyu Cleaner 清爽斗鱼",
		"                by Another_Dreams",
		"                Blog: weijohn.me",
		"",
		"                v6.0.1",
		"                Last updated: 2019/03/22",
		"        ======================================================*/",
		"    /*====================================================",
		"            基于 Chrome 50+ 进行编写,配合ABP或uBlock",
		"              主要针对登陆后的斗鱼,不登陆时有些细节未调整!!! ",
		"        =====================================================*/",
		"    /*临时活动屏蔽区*/",
		" 	#kill-ie,",
		"    .PubgInfo-icon,",
		"  	/*弹幕区屏蔽通知提示语*/",
		"	.sys-tips，",
		"	/*屏蔽右上角的客户端图标的右上角的快速稳定*/",
		"	#header .headerdown-corner，",
		"  	.PaladinPop.，",
		"	.RotaryDraw-enter,",
		"	.PaladinEntry,",
		"	li.fl.summer_acitivity,",
		"    .sharkNote {",
		"        display: none !important;",
		"    }",
		"    /* 斗鱼活动按钮 去除视频下方竞猜、活动等 */",
		"	.action-item",
		"	.more-action-btn-wrap,",
		"    /*巅峰榜排名*/",
		"    .starsgathered,",
		"    .fans201803-tips,",
		"    /*HTML5播放器广告*/",
		"    .QRcode,",
		"    /*去分类广告*/",
		"    #header .head-nav .assort-ad,",
		"    /*去历史和关注的广告条*/",
		"    .f-sign-cont,",
		"    .his-sign-cont,",
		"    /*去个人中心我的任务、贵族、头像圆点*/",
		"    .o-login .l-menu .task,",
		"    /*[[privilege]]*/",
		"    .umes-icon,",
		"    /*房间头部广告*/",
		"    .room-ad-top,",
		"    /*去广告*/",
		"    .search-suggest-ad,",
		"    .chat-top-ad,",
		"    .chat_top_pic,",
		"    .rank-video-ad,",
		"    /*去视频下方主播发帖 直播公告 视频推荐*/",
		"    .PlayerSub,",
		"    /*去弹幕公告*/",
		"    #js-chat-notice,",
		"    /*去视频下方任务*/",
		"    .fl.task-btn,",
		"    /*去聊天区广告*/",
		"    .chat-ad,",
		"    /*去聊天区火箭*/",
		"    .giftbatter-box,",
		"    /*去领鱼丸提示*/",
		"    .pay-task,",
		"    /*去分享扫一扫*/",
		"    .room-mes .btn-group .sq-wrap,",
		"    /*去领鱼丸主播推荐*/",
		"    #js-yw-rmd-rooms,",
		"    .vcode9-sign,",
		"    .myvip--guide--oncar,",
		"    /*去超管推荐*/",
		"    .js-live-room-recommend,",
		"    /*去缩放提示*/",
		"    .pop-zoom-container,",
		"    /*去顶部游戏选项*/",
		"    #header .head-nav>li.funny,",
		"    #header .head-nav .wxr-menu,",
		"    /*去顶部鱼吧选项*/",
		"    #header .head-nav>li.yuba,",
		"    /*主播土豪排行榜*/",
		"    .feedback-report-button,",
		"    /*去举报按钮*/",
		"    .focus-lead,",
		"    /*关注提醒*/",
		"    .anchor-task-icon,.anchor-task-progress,",
		"    /*等级上线提醒*/",
		"    .normallevel-lead,",
		"    /*主播商品推荐*/",
		"    .fishop-anchor-push-box.expanded,",
		"    .fishop-anchor-recommands-box.expanded,",
		"    .day-pay-wrap,",
		"    /*输入框首充徽章*/",
		"    .firstpay-award-icon,",
		"    .firstpay-entrance,",
		"    .firstpay-modal,",
		"    .firstpay-warp {",
		"        display: none !important;",
		"    }",
		"    /*去聊天框粉丝徽章*/",
		"    .fans-entrance {",
		"        display: none !important;",
		"    }",
		"    /*修复屏蔽粉丝徽章导致聊天框的问题*/",
		"    .chat-feat textarea.cs-textarea {",
		"        padding-left: 13px !important;",
		"        width: 250px !important;",
		"    }",
		"    /*修复抢飞机宝箱验证码偏移出屏幕的问题*/",
		"    .geetest_fullpage_click.geetest_float.geetest_wind.geetest_slide3 {",
		"        left: 79%!important;",
		"    }",
		"    /*未登录调整*/",
		"    .no-login {",
		"	    display: none !important;",
		"	    height: 0px !important;",
		"	    margin-bottom: 0px !important;",
		"    }",
		"    .PlayerCaseSub-Main.is-unlogin {",
		"	    top: 0px !important;",
		"    }",
		"    /*房间头部广告*/",
		"    .room-ad-top {",
		"        width: 0px;",
		"        left: 0px;",
		"    }",
		"    /*主播房间信息调整*/",
		"    .btn-group .focus-box {",
		"        top: auto!important;",
		"        bottom: 5px;",
		"        -moz-transform: scale(0.7);",
		"        zoom: 0.7;",
		"    }",
		"    .relate-text .headline {",
		"        width: calc(42% + 105px) !important;",
		"    }",
		"    .relate-text .acinfo-fs-con {",
		"        min-width: calc(42% + 105px) !important;",
		"    }",
		"    .relate-text .headline ,",
		"    .relate-text .acinfo-fs-con ,",
		"    .relate-text .tag-fs-con {",
		"        float: left;",
		"    }",
		"    .relate-text .anchor-impress {",
		"        margin: 3px 0 0!important;",
		"    }",
		"    .relate-text .impress-list {",
		"        max-width: 250px !important;",
		"    }",
		"        /*去皇帝推荐*/",
		"    .room-emperor-recommend {",
		"        display: none !important;",
		"    }",
		"    .room-mes.roommes-bg-small,",
		"    .room-mes.roommes-bg-big {",
		"        background: #fff;",
		"    }",
		"    /*主播头像*/",
		"    .relate-text {",
		"        margin-left: 62px !important;",
		"    }",
		"    .room-mes {",
		"        height: auto !important;",
		"    }",
		"    .room-mes .anchor-pic {",
		"        margin: 2px 0px 0px 2px;",
		"        width: 55px !important;",
		"        height: 55px !important;",
		"    }",
		"    .room-mes .anchor-pic img {",
		"        border-radius: 50%!important;",
		"        box-shadow: 0 0 2px rgba(0, 0, 0, 0.5);",
		"    }",
		"    .anchor-pic .anchor-cover-wrap .cover {",
		"        background: none;",
		"    }",
		"    @media screen and (max-width: 1900px) {",
		"        .relate-text .acinfo-fs-con {",
		"            width: 100% !important;",
		"        }",
		"        .relate-text .anchor-impress {",
		"            margin: 0!important;",
		"            zoom: 0.9;",
		"            -moz-transform: scale(0.9);",
		"        }",
		"        /*主播头像*/",
		"        .relate-text {",
		"            margin-left: 85px !important;",
		"        }",
		"        .room-mes {",
		"            height: 82px !important;",
		"        }",
		"        /*主播头像*/",
		"        .room-mes .anchor-pic {",
		"            margin: 4px 0px 0px 3px;",
		"            width: 75px !important;",
		"            height: 75px !important;",
		"        }",
		"    }",
		"    	.catagory-order-container {",
		"		display: none !important;",
		"	}",
		"    @media screen and (max-width: 1500px) {",
		"        .relate-text .headline {",
		"            width: 320px !important;",
		"            max-width: 320px!important;",
		"        }",
		"        /*礼物*/",
		"        .give-gift {",
		"            margin-left: 10px;",
		"        }",
		"    }",
		"    /* 视频录像按钮 */",
		"    .video-recording {",
		"        display: none!important;",
		"    }",
		"    /* 直播间 */",
		"    .body-flash-fullpage .room-video {",
		"        border-left-width: 0px;",
		"        border-right-width: 0px;",
		"    }",
		"    .room-video {",
		"        border: 1px solid rgba(255, 255, 255, 0.3);",
		"        border-radius: 5px;",
		"        box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.2);",
		"    }",
		"    /*使用HTML5播放器时*/",
		"    .room-video,",
		"    .danmu-container {",
		"        border: 0;",
		"    }",
		"    .danmu-ctrl {",
		"        background: #23272b!important;",
		"        border: 0!important;",
		"        color: #9a9a9a!important;",
		"    }",
		"    /*礼物*/",
		"    .get-yw .yw-collect-box.ywrmd {",
		"        min-height: 140px !important;",
		"    }",
		"    .yw-collect-box {",
		"        top: -180px !important;",
		"        margin-left: -50px !important;",
		"    }",
		"    #js-stats-and-actions {",
		"        margin-top: 5px;",
		"        padding: 2px 22px 2px 19px;",
		"        height: 40px;",
		"        border: 1px solid #e5e4e4;",
		"        border-radius: 5px;",
		"        box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.2);",
		"    }",
		"    .body-flash-fullpage .m-wealth {",
		"        padding-top: 0px!important;",
		"        margin-top: 0px!important;",
		"    }",
		"    /*  鱼翅和充值图标 */",
		"    span.y2.fl,",
		"    a.r-com-btn.getYc.fl {",
		"        display: none!important;",
		"    }",
		"    /*鱼丸可领取时间*/",
		"    .task-Getyw .tip {",
		"        -moz-transform: scale(0.8);",
		"        zoom: 0.8;",
		"    }",
		"    .uinfo-ywyc {",
		"        clear: none !important;",
		"        height: 0px!important;",
		"        margin-top: 10px!important;",
		"    }",
		"    .uinfo-ywyc .m-wealth {",
		"        display: flex !important;",
		"        height: 0px;",
		"    }",
		"    /*去鱼丸领取时的APP下载提示 */",
		"    p.yw-app-des,",
		"    .ft-sign-cont,",
		"    /*微博分享提示*/",
		"    .room-wbshare",
		"    /*未登陆聊天区一个区域*/",
		"    .no-login {",
		"        display: none !important;",
		"    }",
		"    /*去聊天区的特效礼物*/",
		"    .giftbatter-box {",
		"        display: none !important;",
		"        height: 0px;",
		"    }",
		"    /*粉丝聊天条*/",
		"    .chat-cont li.fans-chart,",
		"    .chat-cont li.noble-chart {",
		"        padding: 0px!important;",
		"        margin-left: 0px!important;",
		"        background: none!important;",
		"    }",
		"     /*小姐姐欢迎背景*/",
		"    .girl-cont {",
		"    	line-height: 22px !important;",
		"    	padding: 0px !important;",
		"    }",
		"    .chart-li-girl {",
		"    	background: none !important;",
		"    	height: auto !important;",
		"    }",
		"    /*精简聊天区图标*/",
		"    .chat-task-madel,",
		"    .user-level-wel,",
		"    .motorcade-icon,",
		"    .task-wel,",
		"    .f-phone,",
		"    .pc-client-icon,",
		"    .user-noble-lv,",
		"    .enter-welcome1,",
		"    .status-low-enter,",
		"    /*[[lw-imgs]]*/",
		"    .chat-icon-pad/*[[user-level]]*//*[[fans]]*/",
		"    {",
		"        display: none !important;",
		"    }",
		"    .small-nav>ul>li:nth-of-type(9),",
		"    /*抽屉菜单的游戏*/",
		"    .channel-cate>ul>li:nth-of-type(5)/*抽屉菜单的页游中心*/",
		"    {",
		"        display: none !important;",
		"    }"
	].join("\n");
if (false || (document.location.href.indexOf("https://www.douyu.com/directory") == 0) || (document.location.href.indexOf("https://www.douyu.com/room/my_follow") == 0))
	css += [
		"/* <!-- web直播页广告位 --> */",
		"    .lol-ad {",
		"        display: none !important;",
		"    }",
		"    /* http://www.douyu.com/directory/下的列表 */",
		"    .item-data .unit {",
		"        border: 1px solid #eee;",
		"        background: #eee;",
		"    }",
		"    .left-menu {",
		"        background: #2c2c2c;",
		"    }"
	].join("\n");
if (false || (document.domain == "douyu.com" || document.domain.substring(document.domain.indexOf(".douyu.com") + 1) == "douyu.com"))
	css += [
		"/*====斗鱼首页====*/",
		"   /*页游*/",
		"    .game,",
		"    /*<!--第五行：官方活动-->*/",
		"    /*[[official]]*/",
		"    /*<!--第一行：广告、新闻、推广-->*/",
		"    .row-1,",
		"    .row-3,",
		"    .row-4 {",
		"        display: none !important;",
		"    }"
	].join("\n");
if (false || (document.location.href.indexOf("https://www.douyu.com/cms/zt/") == 0))
	css += [
		"/****** 特别直播间的一些调整 ******/",
		"    /*去分享按钮*/",
		"    .r_share,",
		"    .room_qrcode {",
		"        display: none !important;",
		"    }",
		"    /*关注按钮*/",
		"    .room_mes .btn-group .focus-box {",
		"        top: 0px;",
		"    }",
		"    /***** 活动直播间 *****/",
		"    /*去网页头的游戏*/",
		"    .head .header_nav>li:nth-of-type(4) {",
		"        display: none !important;",
		"    }",
		"    /* 去个人任务 */",
		"    #header .head .header_r .head_user .task {",
		"        display: none !important;",
		"    }",
		"    /**** 礼物区 ****/",
		"    .stats_and_actions {",
		"        height: auto !important;",
		"    }",
		"    /* 任务 */",
		"    .task-Getyw .task {",
		"        display: none !important;",
		"    }",
		"    /* 鱼丸 */",
		"    .uinfo-ywyc {",
		"        position: static;",
		"    }",
		"    .c_cont.clearfix.chat_cont.c_gift_cont_height {",
		"        padding: 5px 2px;",
		"    }",
		"    div#cq_fans {",
		"        margin: 0 -2px;",
		"    }",
		"    .mb15 {",
		"        margin-bottom: 1px;",
		"    }",
		"    .column01 {",
		"        margin-top: 10px;",
		"        margin-bottom: 10px;",
		"    }",
		"    #get_rem {",
		"        top: -180px !important;",
		"    }"
	].join("\n");
if (false || (document.domain == "douyu.com" || document.domain.substring(document.domain.indexOf(".douyu.com") + 1) == "douyu.com"))
	css += [
		"/* 滚动条美化 */",
		"    /* Let\'s get this party started */",
		"     ::-webkit-scrollbar {",
		"        width: 8px;",
		"        height: 8px;",
		"    }",
		"    /* Track */",
		"     ::-webkit-scrollbar-track {",
		"        /* -webkit-box-shadow: inset 0 0 5px rgba(255, 153, 0, 0.6);*/",
		"        background-color: #F5F5F5;",
		"    }",
		"    /* Handle */",
		"     ::-webkit-scrollbar-thumb {",
		"	border-radius:4px;",
		"        background-color: #FF9900;",
		"        background-image: -webkit-linear-gradient(45deg, ",
		"                                    rgba(255, 255, 255, .2) 25%, ",
		"                                    transparent 25%, ",
		"                                    transparent 50%, ",
		"                                    rgba(255, 255, 255, .2) 50%, ",
		"                                    rgba(255, 255, 255, .2) 75%, ",
		"                                    transparent 75%, ",
		"                                    transparent);",
		"    }"
	].join("\n");
if (false || (document.domain == "douyu.com" || document.domain.substring(document.domain.indexOf(".douyu.com") + 1) == "douyu.com"))
	css += [
		"/****** 尝试适配新版本 ******/",
		" .TurntableLottery {",
		"    display: none !important;",
		"}",
		".RewardModal-recommendList, .RewardModal-text, .WeekRank, .Title-blockInline, .Title-roomOtherBottom, .code-box-15b952, .recommendApp-0e23eb,",
		"/*导航*/",
		" .Header-holder, .Header-menu-link:nth-of-type(4), .Header-menu-link:nth-of-type(5) > .public-DropMenu, .HeaderBroadcast, .Download > .public-DropMenu, #header .headerdown-corner, .Download-iconAdd, .video-entry.fl, .funny.fl, .fl.o-broadcast, .fl.o-download {",
		"    display: none !important;",
		"}",
		"/*个人*/",
		" .Task, .Promotion {",
		"    display: none !important;",
		"}",
		"/*-------直播间------*/",
		".PaladinWeek,",
		".player_h5_adDom,",
		".yearFestival201810Mini,",
		".multiBitRate-da4b60,",
		"/*互动竞猜*/",
		".guessGameContainer.is-normalRoom,",
		"/*弹幕区屏蔽通知提示语*/",
		".BarrageTips--active,",
		"/*亲密互动*/",
		".normalDiv-8b686d {",
		"    display: none !important;",
		"}",
		"/*-------礼物区------*/",
		"#js-room-activity,",
		".ToolbarActivityArea .ActivityItem:not([data-flag=anchor_quiz]),",
		".RotaryDraw-enter.JS_RotaryDraw_APP, .PlayerToolbar-ycInfo, .PlayerToolbar-getYCArea, .PlayerToolbar-Task, .FirstRecharge, .layout-Bottom {",
		"    display: none !important;",
		"}",
		".RewardModule-tips {",
		"    top: 24px!important;",
		"}",
		".is-fullScreenPage .layout-Player-toolbar {",
		"	height: 70px!important;",
		"}",
		"",
		".is-fullScreenPage .PlayerToolbar {",
		"	padding: 14px 15px 9px!important;",
		"}",
		".layout-Player-toolbar {",
		"    border-top-style: groove!important;",
		"    border-top-width:1px !important;",
		"    height: 50px!important;",
		"    margin-top: 10px!important;",
		"}",
		".PlayerToolbar {",
		"    padding: 5px!important;",
		"}",
		".PlayerToolbar-Wealth {",
		"    width: auto!important;",
		"    margin-top: 10px!important;",
		"}",
		"",
		"/*-------标题栏------*/",
		" .YzQualifyingEntry,.YzRankList,.GiftStarIcon,",
		" .anchor-pic .anchor-cover-wrap .text,.ComSuperscript,",
		" .pk-grading-con, .StarsGathered, .YubaGroup-text, .HugeStarRanking, .Title-followFocus {",
		"    display: none !important;",
		"}",
		".Title{",
		"    height: 66px !important;",
		"    padding-left: 70px !important;",
		"}",
		".Title-anchorPic, .Title--noAnchorImpress .Title-anchorPic, .Title--noAnchorImpress .YubaGroup-anchorCoverWrap {",
		"    width: 65px!important;",
		"    height: 65px!important;",
		"}",
		".Title-anchorInfo {",
		"    float: right!important;",
		"    margin-top: -23px!important;",
		"    margin-right: 5px!important;",
		"}",
		".layout-Player-title {",
		"    min-height: 65px!important;",
		"}",
		".RewardModal.super {",
		"    min-height: 110px!important;",
		"}",
		".Title-roomOtherTop {",
		"    zoom: 0.7!important;",
		"    -moz-transform: scale(0.7);",
		"    right: 20px!important;",
		"}",
		"/*圆角头像*/",
		" .Title-anchorPicBack {",
		"    border-radius: 50%!important;",
		"    box-shadow: 0 0 2px #00000080;",
		"}",
		".YubaGroup-cover {",
		"    background:none!important;",
		"}",
		"/*---------聊天弹幕区---------*/",
		"",
		"/*排行榜*/",
		"/*去酬勤榜*/",
		".fans-rank {",
		"    display: none!important;",
		"    height: 0px!important;",
		"}",
		" .layout-Player-rank, .layout-Player-rankAll {",
		"    display: none !important;",
		"}",
		".layout-Player-barrage {",
		"    top: 38px !important;",
		"}",
		"    /*聊天弹幕*/",
		"    .PlayerCaseSub-Main .chat-cont {",
		"        top: 0px !important;",
		"        border-radius: 4px 4px 0px 0px;",
		"    }",
		"",
		".Medal, .BarrageBanner, .Barrage-icon, .Barrage-userEnter, .FansMedal-name, .Motor, .UserLevel, .Summer_Medal_low, .ChatEffect {",
		"    display: none !important;",
		"}",
		".Barrage-message, .Barrage-notice {",
		"    display: none !important;",
		"}",
		".Barrage-noble, .Barrage-nobleImg, .FansMedal {",
		"    width: 0px!important;",
		"    height: 0px!important;",
		"    background-image: none!important;",
		"}",
		".Barrage-listItem {",
		"    margin-bottom: 0px!important;",
		"    margin-top: 0px!important;",
		"}",
		".Barrage-notice--noble {",
		"    padding: 0px!important;",
		"    background: #f8f8f8!important;",
		"    border-top: 1px solid #f8f8f8!important;",
		"    border-bottom: 1px solid #f8f8f8!important;",
		"    background-color: #f8f8f8!important;",
		"}",
		".Barrage--paddedBarrage {",
		"    padding: 0px 10px!important;",
		"}",
		".js-noblefloating-barragecont.Barrage-notice--noble {",
		"    padding-left: 10px!important;",
		"}",
		".layout-Main {",
		"    padding-top: 10px!important;",
		"}",
		"/*---------左侧菜单---------*/",
		"a.AsideUnfold-channelItem.channelGame,",
		"a.AsideFold-listIitem.channelGame {",
		"    display: none!important;",
		"}"
	].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
